version: '3.9'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - env
    ports:
      - 5432

  scrapper:
    build: ./scrapper
    ports:
      - 5000
    env_file:
      - env
    depends_on:
      db:
        condition: service_started

  server:
    build: ./web
    ports:
      - '8080:8080'
    env_file:
      - env
    depends_on:
      db:
        condition: service_started
      scrapper:
        condition: service_started

  adminer:
    image: adminer
    restart: always
    depends_on:
      db:
        condition: service_started
    ports:
      - '8888:8080'
