version: '3.9'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - env_vars
    ports:
      - '5432:5432'

  scrapper:
    build: ./scrapper
    ports:
      - '8000:5000'
    env_file:
      - env_vars
    depends_on:
      db:
        condition: service_started

  server:
    build: ./web
    ports:
      - '8080:8080'
    env_file:
      - env_vars
    depends_on:
      db:
        condition: service_started
      scrapper:
        condition: service_started
